name: CI/CD Pipeline for Book Tracker API 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
        
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "docker-compose.yml"
    
      # Step 4: Setup test
      - name: Setup Test
        run: |
            go test -v -coverpkg=./internal/db,./internal/handlers,./internal/repository ./tests/... -coverprofile=coverage.out
            go tool cover -func=coverage.out

     