name: CI/CD Pipeline for Book Tracker API 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
        
      # Step 4: Set up Docker Compose and start services
      - name: Set up Docker Compose and start services
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "docker-compose.yml"

      # Step 5: Run Go Tests Inside Docker
      - name: Run Go Tests Inside Docker
        run: |
          docker compose exec -T app sh -c "go test -v -coverpkg=./internal/db,./internal/handlers,./internal/repository ./tests/... -coverprofile=coverage.out"

      # Step 6: Generate and show the coverage report
      - name: Generate Coverage Report
        run: |
          docker compose exec -T app sh -c "go tool cover -func=coverage.out"
        
