name: CI/CD Pipeline for Book Tracker API With Keploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
        
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "docker-compose.yml"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Setup Keploy
      - name: Wait for Application to be Ready
        run: |
         echo "Waiting for application to be ready..."
         for i in {1..30}; do
          if curl --silent --head --fail http://localhost:8080; then
            echo "Application is ready!"
            break
          else
            echo "Waiting for application to be ready... $i"
            sleep 5
          fi
         done

      # Step 2: Run Keploy Test Suite
      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=03d24177-315c-4ee1-a3ac-64ed0ab38567 --base-path http://localhost:8080/books --cloud
